name: llm-sa
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - pip:
    - einops==0.4.0
    - higher==0.2.1
    - hydra-core==1.2.0
    - transformers==4.40.0
    - datasets==1.18.3
    - matplotlib==3.6.1
    - spacy==3.4.1
    - scipy==1.9.2
    - scikit-learn==1.0.2
    - nltk==3.7
    - jupyter==1.0.0
    - nlpaug==1.1.11
